name: Build plugin jars

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build dengan Maven
        run: mvn -B clean package

      - name: Upload jar - Paper
        uses: actions/upload-artifact@v4
        with:
          name: bedrockbypass-paper
          path: bedrockbypass-paper/target/*.jar

      - name: Upload jar - Velocity
        uses: actions/upload-artifact@v4
        with:
          name: bedrockbypass-velocity
          path: bedrockbypass-velocity/target/*.jar
